backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles:
    - admin
  commit_messages: 
    create: (CMS) Created {{collection}} post "{{slug}}"
    update: (CMS) Updated {{collection}} post "{{slug}}"
    delete: (CMS) Deleted {{collection}} post "{{slug}}"
    uploadMedia: (CMS) Uploaded new media to "{{path}}"
    deleteMedia: (CMS) Deleted media from "{{path}}"

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/img/cms_uploads" # Media files will be stored in the repo under images/uploads

media_library:
  name: cloudinary
  config:
    cloud_name: flashdeviant
    api_key: 141447273721362

site_url: https://shanks.me

display_url: https://shanks.me

logo_url: https://shanks.me/assets/img/cms_logo.svg

collections: